beer_recommend_prj/urls.py
from django.http import HttpResponse
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
from django.conf.urls.static import static
from beer_recommend_prj import settings


def root(request):
    return redirect("/search/")
    # HttpResponse("/two_trillion를 추가해 '오늘 시간 비어: 맥주 추천 페이지'로 이동해주세요")


urlpatterns = [
    path('', root),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('search/', include('search.urls')),
    path('community/', include('community.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/urls.py
from django.urls import path
from search import views


app_name = 'search'
urlpatterns = [
     path('', views.keyword),
     path('recommend/', views.predict),
     path('beerprofile/<int:pk>/', views.search_detail, name="beerprofile"),
     path('search/', views.search),
     path('ranking/', views.ranking),
     path('like/<int:pk>/', views.like, name="like"),
]


    

search/models.py
from django.db import models


class Beer(models.Model):
    id = models.AutoField(primary_key=True)
    big_kind = models.CharField(max_length=100)
    kind = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    brewery = models.CharField(max_length=200)
    country = models.CharField(max_length=100)
    abv = models.CharField(max_length=100)
    average = models.CharField(max_length=100)
    ratings = models.CharField(max_length=100)
    reviews = models.CharField(max_length=100)
    status = models.CharField(max_length=100)
    body = models.FloatField()
    sweet = models.FloatField()
    fruity = models.FloatField()
    hoppy = models.FloatField()
    malty = models.FloatField()
    like_users = models.ManyToManyField('account.User', related_name='like_beers', blank=True)
    like_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name

search/forms.py
from django import forms

#class SearchFormView(FormView):
 #   form_class = PostSearchForm
  #  template_name = 'blog/post_search.html'

search/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from search.models import Beer
from math import pi
import matplotlib.pyplot as plt
import random
import logging
import pandas as pd
from search.ml import beer_model

MAX_LIST_CNT = 30
MAX_PAGE_CNT = 5

logger = logging.getLogger('tipper')
logger.setLevel(logging.DEBUG)
logger.addHandler(logging.StreamHandler())


def keyword(request):
    beer_list = Beer.objects.all()
    keyword = request.GET.get('keyword', '')

    if keyword:
        beer_list = beer_list.filter(
            Q(name__icontains=keyword) |
            Q(brewery__icontains=keyword) |
            Q(country__icontains=keyword)
        )

        template_name = "search/keyword_list.html"
    else:
        template_name = "search/keyword_page.html"

    paginator = Paginator(beer_list, MAX_LIST_CNT)
    page = request.GET.get('page', 1)
    pagenated_beer_list = paginator.get_page(page)

    last_page_num = 0
    for last_page in paginator.page_range:
        last_page_num = last_page_num + 1
        # 현재 페이지가 몇번째 블럭인지
        current_block = ((int(page) - 1) / MAX_PAGE_CNT) + 1
        current_block = int(current_block)
        # 페이지 시작번호
        page_start_number = ((current_block - 1) * MAX_PAGE_CNT) + 1
        # 페이지 끝 번호
        page_end_number = page_start_number + MAX_PAGE_CNT - 1

    context_beer_list = {'last_page_num': last_page_num,
                         'page_start_number': page_start_number,
                         'page_end_number': page_end_number,
                         'pagenated_beer_list': pagenated_beer_list,
                         'keyword': keyword}
    # print(keyword)
    return render(request, template_name, context=context_beer_list)


# @csrf_exempt  # CSRF Token 체크를 하지 않겠습니다.
def search(request):
    beer_list = Beer.objects.all()
    ch_category_list = request.GET.getlist("chCategory")
    ch_country_list = request.GET.getlist("chCountry")
    search_keyword = request.GET.get('search_keyword', '')

    if ch_category_list or ch_country_list:
        if ch_category_list:
            beer_list = beer_list.filter(
                Q(big_kind__in=ch_category_list)
            )
        if ch_country_list:
            beer_list = beer_list.filter(
                Q(country__in=ch_country_list)
            )
        template_name = "search/search_list.html"
    else:

        if search_keyword:
            beer_list = beer_list.filter(
                Q(name__icontains=search_keyword) |
                Q(brewery__icontains=search_keyword) |
                Q(country__icontains=search_keyword)
            )
            template_name = "search/keyword_list.html"
        else:
            template_name = "search/search_page.html"

    paginator = Paginator(beer_list, MAX_LIST_CNT)
    page = request.GET.get('page', 1)
    pagenated_beer_list = paginator.get_page(page)

    last_page_num = 0
    for last_page in paginator.page_range:
        last_page_num = last_page_num + 1
        # 현재 페이지가 몇번째 블럭인지
        current_block = ((int(page) - 1) / MAX_PAGE_CNT) + 1
        current_block = int(current_block)
        # 페이지 시작번호
        page_start_number = ((current_block - 1) * MAX_PAGE_CNT) + 1
        # 페이지 끝 번호
        page_end_number = page_start_number + MAX_PAGE_CNT - 1

    if ch_category_list or ch_country_list:
        if ch_category_list:
            ch_category_list = ch_category_list[0]
        if ch_country_list:
            ch_country_list = ch_country_list[0]
    else:
        pass

    context_beer_list = {'last_page_num': last_page_num,
                         'page_start_number': page_start_number,
                         'page_end_number': page_end_number,
                         'ch_category_list': ch_category_list,
                         'ch_country_list': ch_country_list,
                         'keyword': search_keyword,
                         'pagenated_beer_list': pagenated_beer_list}

    return render(request, template_name, context=context_beer_list)


def predict(request):
    user_feature = [
        request.GET.get('sweet'),
        request.GET.get('body'),
        request.GET.get('fruit'),
        request.GET.get('hoppy'),
        request.GET.get('malty'),
    ]
    if all(user_feature) is False:
        predict_beer = None
    else:
        user_feature = list(map(float, user_feature))
        predict_beer = beer_model.predict(user_feature)
    kind_list = Beer.objects.all().order_by('-reviews')
    if predict_beer:
        kind_list = kind_list.filter(
            Q(kind__icontains=predict_beer))[:10]

        df = pd.read_csv('final_proj_train_beer_ratings.csv')
        gf = ''
        print(df)
        df = df.drop(['스타일대분류', '양조장명', '제조국가명', '도수', '평균점수', '리뷰수', '현재상태', '평가수', 'Full Name'], axis=1)
        df['스타일소분류'] = df['스타일소분류'].str.replace(' ', '')
        print(predict_beer)
        gf = df[df['스타일소분류'] == predict_beer]
        print(gf)
        my_favor = pd.DataFrame(columns=['Body', 'Sweet', 'Fruity', 'Hoppy', 'Malty'])
        my_input = user_feature
        my_favor.loc[my_favor.shape[0] + 1] = my_input
        gf = gf.drop(['Astringent', 'Alcoholic', 'Bitter', 'Sour', 'Salty', 'Spices'], axis=1)
        print(gf)
        df_ac = pd.concat([gf, my_favor])
        df_ac.fillna(0)
        df_ac.fillna({'스타일소분류': 'recommand'}, inplace=True)
        df_ac = df_ac.astype({'Body': 'float64'})  ## 데이터 타입 바꿔 주기
        df_ac = df_ac.astype({'Sweet': 'float64'})
        df_ac = df_ac.astype({'Fruity': 'float64'})  ## 데이터 타입 바꿔 주기
        df_ac = df_ac.astype({'Hoppy': 'float64'})
        df_ac = df_ac.astype({'Malty': 'float64'})

        df_ab = df_ac.reset_index()

        a = df_ab['스타일소분류'].str.contains('recommand')
        # 해당 지역의 인덱스 찾기
        df2 = df_ab[a]
        print(df2.iloc[0])
        df2 = df2.drop(['index'], axis=1)
        print(df2)
        df3 = df2.drop(['스타일소분류', '맥주명'], axis=1)
        print("--------------------")
        df_ac = df_ac.sub(df3.iloc[0], axis=1)
        df_ad = df_ac.sum(axis=1)
        print(df_ab)
        print(df_ad)

        df_name = df_ab['맥주명']

        df_final = pd.DataFrame(df_name, columns=['맥주명']).reset_index(drop=True)

        df_af = pd.DataFrame(df_ad, columns=['수치']).reset_index(drop=True)

        e = pd.concat([df_final, df_af], axis=1)

        e['수치'] = e['수치'].abs()
        f = e.sort_values(by=['수치']).reset_index(drop=True)

        ffinal = f['맥주명'].iloc[1:6].to_list()
        print(ffinal)

        prename_list = Beer.objects.all()

        if ffinal:
            prename_list = prename_list.filter(
                Q(name__in=ffinal))[:5]

    else:
        prename_list = ''
    return render(request, "search/recommend.html",
                  {'predict_beer': predict_beer, 'kind_list': kind_list, 'prename_list': prename_list})


@login_required
def search_detail(request, pk):

    search_detail = Beer.objects.get(id=pk)

    import matplotlib
    import matplotlib.font_manager as fm

    fm.get_fontconfig_fonts()
    font_location = 'C:\Windows\Fonts\malgun.ttf'  # For Windows
    font_name = fm.FontProperties(fname=font_location).get_name()
    matplotlib.rc('font', family=font_name)

    df = pd.read_csv('final_train_beer_ratings_Ver_rader model1.csv', encoding='utf-8-sig', index_col=0)
    aaa = df['Full Name'].iloc[pk]
    cc = df[df['Full Name'] == '%s' % aaa]

    cc = cc[
        ['Body', 'Sweet', 'Fruity', 'Hoppy', 'Malty']]
    cc = cc.rename(columns={'Body': '바디감', 'Sweet': '당도', 'Fruity': '과일향', 'Hoppy': '홉향', 'Malty': '맥아향'})
    dfR = cc
    n = 0
    angles = [x / 5 * (2 * pi) for x in range(5)]  # 각 등분점
    angles += angles[:1]  # 시작점으로 다시 돌아와야하므로 시작점 추가
    my_palette = plt.cm.get_cmap("Set2", 5)
    fig = plt.figure(figsize=(8, 8), dpi=100)
    fig.set_facecolor('white')
    color = ["#" + ''.join([random.choice('0123456789ABCDEF') for j in range(6)])][0]
    labels = dfR.columns[:]

    data = dfR.iloc[0].tolist()
    data += data[:1]

    ax = plt.subplot(1, 1, 1, polar=True)
    ax.set_theta_offset(pi / 2)  # 시작점
    ax.set_theta_direction(-1)  # 그려지는 방향 시계방향

    plt.xticks(angles[:-1], labels, fontsize=27)  # x축 눈금 라벨
    ax.tick_params(axis='x', which='major', pad=30)  # x축과 눈금 사이에 여백을 준다.

    ax.set_rlabel_position(0)  # y축 각도 설정(degree 단위)
    plt.yticks([-1, 0, 1, 3, 5], ['', '', '', '', ''], fontsize=10)  # y축 눈금 설정
    plt.ylim(-1, 5)

    ax.plot(angles, data, color=color, linewidth=2, linestyle='solid')  # 레이더 차트 출력
    ax.fill(angles, data, color=color, alpha=0.4)  # 도형 안쪽에 색을 채워준다.

    plt.title('', size=20, color=color, x=0.5, y=1, ha='center')  # 타이틀은 캐릭터 클래스로 한다.

    plt.tight_layout(pad=5)  # subplot간 패딩 조절

    plt.savefig('static/beerimg.png')

    # ------------------------------

    df = pd.read_csv('final_proj_train_beer_ratings.csv')
    gn = ''

    df = df.drop(['스타일대분류', '양조장명', '제조국가명', '도수', '평균점수', '리뷰수', '현재상태', '평가수', 'Full Name'], axis=1)

    gf = df[df['스타일소분류'] == search_detail.kind]

    my_favor = pd.DataFrame(columns=['맥주명', 'Body', 'Sweet', 'Fruity', 'Hoppy', 'Malty'])
    f0 = search_detail.name
    f1 = search_detail.body  # value 넣기
    f2 = search_detail.sweet
    f3 = search_detail.fruity
    f4 = search_detail.hoppy
    f5 = search_detail.malty
    my_input = [f0, f1, f2, f3, f4, f5]
    my_favor.loc[my_favor.shape[0] + 1] = my_input
    gf = gf.drop(['Astringent', 'Alcoholic', 'Bitter', 'Sour', 'Salty', 'Spices'], axis=1)
    df_ac = pd.concat([gf, my_favor])
    df_ac = df_ac.astype({'Body': 'int64'})  ## 데이터 타입 바꿔 주기
    df_ac = df_ac.astype({'Sweet': 'int64'})
    df_ac = df_ac.astype({'Fruity': 'int64'})  ## 데이터 타입 바꿔 주기
    df_ac = df_ac.astype({'Hoppy': 'int64'})
    df_ac = df_ac.astype({'Malty': 'int64'})

    df_ab = df_ac.reset_index()

    a = df_ab['맥주명'].str.contains(search_detail.name)  # 해당 지역의 인덱스 찾기

    df2 = df_ab[a]

search/templates/search/base.html
{% extends "base.html" %}

search/templates/search/keyword_list.html
{% extends 'search/base.html' %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% load static %}
<link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">

<style>
    table, th, td {
    }
    td {
        text-align: center;
    }
</style>
{% block content %}
    <div class='row'>
        <div class='col-sm-9'>
            <form action="" method="get" class="form-search d-flex align-items-stretch mb-3 aos-init aos-animate">
                <input type="text" class="form-control" name="search" placeholder={{ keyword }}>
                <button type="submit" class="btn btn-primary">Search</button>
            </form>
            {% if not pagenated_beer_list %}

                <h3>검색 결과가 없습니다! 다른 키워드를 검색해 보는 건 어떠세요? </h3>

            {% else %}
                <h3>{{ keyword }}에 대한 검색 결과</h3>
                <hr style="line: solid 10px black;">
                {% for beer in pagenated_beer_list %}
                    <h4><a href="/search/beerprofile/{{ beer.id }}/">{{ beer.name }}</a></h4>
                    <h6>맥주 스타일: {{ beer.kind }}</h6>
                    <h6>양조장 이름: {{ beer.brewery }}</h6>
                    <h6>제조 국가: {{ beer.country }}</h6>
                    <hr style="line: solid 10px black;">
                {% endfor %}
            {% endif %}
        </div>
        <div class='col-sm-3'>

        </div>
    </div>
    <hr>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if pagenated_beer_list.has_previous %}
            <li class="page_item">
                <a class="page-link" href="?keyword={{ keyword }}&page=1">처음</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?keyword={{ keyword }}&page={{ pagenated_beer_list.previous_page_number }}">이전</a>
            </li>
        {% else %}
            <li class="page_item">
                <a class="page-link" href="#">처음</a>
            </li>
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
            </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in pagenated_beer_list.paginator.page_range %}
            {% if page_start_number <= page_number and page_end_number >= page_number %}
                {% if page_number == pagenated_beer_list.number %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="?keyword={{ keyword }}&page={{ page_number }}">{{ page_number }}</a>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?keyword={{ keyword }}&page={{ page_number }}">{{ page_number }}</a>
                    </li>
                {% endif %}
            {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if pagenated_beer_list.has_next %}
            <li class="page-item">
                <a class="page-link" href="?keyword={{ keyword }}&page={{ pagenated_beer_list.next_page_number }}">다음</a></li>
            <li class="page_item">
                <a class="page-link" href="?keyword={{ keyword }}&page={{ last_page_num }}">마지막</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
            </li>
            <li class="page_item">
                <a class="page-link" href="#">마지막</a>
            </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    <a href="{{ request.build_absolute_uri }}" style="text-decoration-line: none;">Back to top</a>
{% endblock %}

search/templates/search/keyword_page.html
{% extends "search/base.html" %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% load static %}
<link rel="stylesheet" href="{% static 'style.css?after' %}" type="text/css">

{% block title %}Home{% endblock %}
{% block content %}
    <style>
        .box {
            width: 100%;
            height: 50%;
            margin: 40px auto;
        }
        body {
        background-color: #ADD8E6;
        }

    </style>
    <body>
    <div style="padding:20px;"></div>
    <img src="https://media1.giphy.com/media/xuPJrZiruRQ1KRr9Ea/giphy.gif" class="img-fluid" alt="..." style="margin-left: auto; margin-right: auto; display: block;"/>
    <div class='box'>
        <form action="" method="get">
            <div class="form-search d-flex align-items-stretch mb-3 aos-init aos-animate">
                <input type="text" class="form-control" name="keyword" placeholder="Name, Brewery, Style... ">
                <button type="summit" class="btn text-white" style="background-color: #68B984"><b>search</b></button>
            </div>
        </form>
    </div>
</body>
{% endblock %}

search/templates/search/ranking_beer.html
{% extends 'search/base.html' %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% load static %}
<link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">
<style>
    table, th, td {
    }
    td {
        text-align: center;
    }
</style>
{% block content %}
    <div class="container-lg">
        <table class="table">
            <td height="250">
                <h1>한 달 간의 순위를 집계해 드립니다</h1>
                <h3>가족, 친구, 연인을 위해 시간을 beer 보는 건 어때요?</h3>
            </td>
        </table>
        <div style="padding:20px;"></div>

        <div class='row'>
            <div class='col-sm-4'>
                <table class="table">
                    <thead>
                    <tr><h3 style=text-align:center;>월간 인기 맥주 순</h3></tr>
                    </thead>
                    <tbody>
                    {% for rev in review_ranking %}
                        <tr height="70">
                            <th style="background-color: #FED049">{{ forloop.counter }}</th>
                            <td>           </td>
                            <td><h6><a href = "/search/beerprofile/{{ rev.id }}">{{ rev.name }}</a></h6></td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
            <div class='col-sm-4'>
                <table class="table">
                    <thead>
                    <tr><h3 style=text-align:center;>월간 평점 맥주 순</h3></tr>
                    </thead>
                    <tbody>
                    {% for aver in average_ranking %}
                        <tr height="70" >
                            <th style="background-color: #FED049">{{ forloop.counter }}</th>
                            <td>           </td>
                            <td><h6><a href = "/search/beerprofile/{{ aver.id }}">{{ aver.name }}</a></h6></td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
            <div class='col-sm-3'>
                <h1>
                    <div class='col-sm-3'>
                        <div style="padding:20px;"></div>
                        <div class="card" style="width: 25rem;" >
                            <img class="img-fluid" src="{% static '맥주축제.jpg' %}" alt="맥주 광고 이미지" width="400" height="300">
                            <div class="card-body">
                                <h5 class="card-text">내일이 즐거운 대덕구에서 개최하는 먹거리, 볼거리, 놀거리 2022 대덕거리 맥주 축제에 참여하고 다양한 맥주를 경험하세요</h5>
                            </div>
                        </div>
                    </div>
                </h1>
            </div>
        </div>
    </div>
{% endblock %}

search/templates/search/search_detail.html
{% extends 'search/base.html' %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% load static %}
<link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">

{% block content %}
    <style>
        .card-header{
            background-color: #FED049;
        }
        h2{ font-weight: 500;
            font-family: 'Kanit', sans-serif;
        }

        .star-rating {
            display: flex;
            flex-direction: row-reverse;
            font-size: 2.25rem;
            line-height: 2.5rem;
            justify-content: space-around;
            padding: 0 0.2em;
            text-align: center;
            width: 5em;
        }

        .star-rating input {
            display: none;
        }

        .star-rating label {
            -webkit-text-fill-color: transparent; /* Will override color (regardless of order) */
            -webkit-text-stroke-width: 2.3px;
            -webkit-text-stroke-color: #2b2a29;
            cursor: pointer;
        }

        .star-rating :checked ~ label {
            -webkit-text-fill-color: gold;
        }

        .star-rating label:hover,
        .star-rating label:hover ~ label {
            -webkit-text-fill-color: #fff58c;
        }
        .box {
            margin-bottom : 20px;
            padding-top : 20px;
            padding-right : 10px;
            padding-bottom: 30px;
            padding-left: 30px;
            border : 1px solid #fd9400;
            border-radius : 5px;
        }
        hr {
            height: 1px;
            background-color: black;
        }
    </style>
    <div class='row'>
        <div style="padding:20px;"></div>
        <div class='col-sm-9'>
            <h5>스타일 대분류 {{ search_details.big_kind }} >> 스타일 소분류 {{ search_details.kind }}</h5>
            <hr style="border: line 15px black;">
            <div class="row">
                <div class="box">
                    <div class='col-sm-10'>
                        <div style="padding:15px;"></div>
                        <a href="{% url "search:like" search_details.id %}">
                            {% if user in search_details.like_users.all %}
                                <i class="fa-solid fa-heart-circle-minus"> Not My Beer</i>
                            {% else %}
                                <i class="fa-solid fa-heart-circle-plus"> To My Beer</i>
                            {% endif %}
                        </a>
                        <div style="padding:5px;"></div>
                        <h2> {{ search_details.name}} </h2>
                        <div style="padding:5px;"></div>

                        <div class='col-sm-9'>
                            <table class="table table-hover">
                                <tbody>
                                <tr>
                                    <th style="width: 200px">맥주이름</th>
                                    <td>{{ search_details.name }}</td>
                                </tr>

                                <tr>
                                    <th style="width: 200px">대분류 스타일</th>
                                    <td>{{ search_details.big_kind }}</td>
                                </tr>
                                <tr>
                                    <th style="width: 200px">소분류 스타일</th>
                                    <td>{{ search_details.kind }}</td>
                                </tr>
                                <tr>
                                    <th style="width: 200px">양조장 이름</th>
                                    <td>{{ search_details.brewery }}</td>
                                </tr>
                                <tr>
                                    <th style="width: 200px">알코올 도수</th>
                                    <td>{{ search_details.abv }}%</td>
                                </tr>
                                <tr>
                                    <th style="width: 200px">판매 상태</th>
                                    <td>
                                        {% if search_details.status == 'Active' %}
                                            <h5>구매 가능</h5>
                                        {% else %}
                                            <h5>구매 불가</h5>
                                        {% endif %}
                                    </td>
                                </tr>
                                <tr>
                                    <th style="width: 200px">평 점</th>
                                    <td> {{ search_details.average }}</td>
                                </tr>
                                </tbody>
                            </table>
                            <h5>
                                <i class="fa-solid fa-beer-mug-empty"> {{ search_details.like_count }}
                                </i></h5>
                        </div>
                    </div>
                    <img class=img-fluid src='/static/beerimg.png' alt="My Image"
                         style="float: right; width:360px; height:360px; position: absolute; left: 47.25%; top:42%;">
                </div>
            </div>
            <div style="padding:5px;"></div>
            <hr style="line: solid 10px black;">
            <div style="padding:15px;"></div>
            <div class="card mb-2">
                <div class="card-header">
                    <i class="fa fa-comment fa"></i> 맥주 리뷰
                </div>
                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <textarea class="form-control" id="exampleFormControlTextarea1" rows="6"></textarea>
                            <div class="col-sm-2">
                                <div class="star-rating space-x-4 mx-auto">
                                    <input type="radio" id="5-stars" name="rating" value="5" v-model="ratings"/>
                                    <label for="5-stars" class="star pr-4">★</label>
                                    <input type="radio" id="4-stars" name="rating" value="4" v-model="ratings"/>
                                    <label for="4-stars" class="star">★</label>
                                    <input type="radio" id="3-stars" name="rating" value="3" v-model="ratings"/>
                                    <label for="3-stars" class="star">★</label>
                                    <input type="radio" id="2-stars" name="rating" value="2" v-model="ratings"/>
                                    <label for="2-stars" class="star">★</label>
                                    <input type="radio" id="1-star" name="rating" value="1" v-model="ratings" />
                                    <label for="1-star" class="star">★</label>
                                </div>
                            </div>
                            <button type="button" class="btn btn-warning" style="float: right" onClick="javascript:addReply();">리뷰 작성</button>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class='col-sm-3'>
            <div class="box" style="border-color: white">
                <div style="padding:5px;"></div>
                <h3>지금 보고있는 맥주가 취향저격이라면!</h3>
                <div style="padding:10px;"></div>
                <table>
                    {% for na in name_list %}
                        <tbody>
                        <tr height="92">
                            <th style="background-color: #FED049; color: white; width: 50px" >{{ forloop.counter }}</th>
                            <td><h6><a href = "/search/beerprofile/{{ na.id }}">{{ na.name }} ( {{ na.country }} )</a></h6></td>
                        </tr>
                        </tbody>
                    {% endfor %}
                </table>
                <div style="padding:10px;"></div>
                <div class="card" style="width: 265px; height: 410px">
                    <div class="card-header" style="height:40px; background-color: white">
                        <h5>AD</h5>
                    </div>
                    <img class="img-fluid" src="{% static 'kozel_dark.png' %}" alt="맥주 광고 이미지" width="250" height="430">
                    <div class="card-BODY">
                        <h6 class="card-text">코젤 다크는 다크 맥아의 독특한 혼합법을 사용한 전통 제조법으로 맥아의 향과 맛을 완벽히 보완해주어 매혹적이고 깊이 있는 갈색빛의 부드러운 카라멜 향을 선사합니다.</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}